[versions]
activityComposeVersion = "1.8.2"
coilVersion = "2.5.0"
coreKtxVersion = "1.12.0"
espressoCoreVersion = "3.5.1"
hiltNavigationComposeVersion = "1.2.0"
hiltVersion = "2.50"
junit = "1.1.5"
junitVersion = "4.13.2"
lifecycleRuntimeKtxVersion = "2.7.0"
materialAndroidVersion = "1.6.3"
materialIconsExtendedVersion = "1.6.3"
navVersion = "2.7.7"
interceptorVersion = "4.12.0"
retrofitVersion = "2.9.0"
roomVersion = "2.6.1"
compose-bom = "2024.02.02"
agp = "8.2.2"
kotlin = "1.9.0"
ksp-compiler = "1.9.0-1.0.12"
youtube-player = "12.1.0"
googleServicesVersion = "4.4.1"
firebaseFirestoreVersion = "24.10.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtendedVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
material-android = { module = "androidx.compose.material:material-android", version.ref = "materialAndroidVersion" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "interceptorVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
room-paging = { module = "androidx.room:room-paging", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

youtube-player-view = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtube-player" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServicesVersion" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestoreVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kspCompiler = { id = "com.google.devtools.ksp", version.ref = "ksp-compiler" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion"}